### ISSUE TITLE
RedisClient Connection

### ISSUE THREAD

**Issue by mbordash** [juanf/phpbloomfilter#1]
Hi,

How can I use an existing connection to my Redis backend that I've established earlier in my controller? For example, here's how I connect now for other Redis uses:

`$redis = new Redis();
$redis->pconnect(REDIS_HOST, REDIS_PORT);
$redis->auth(REDIS_AUTH);`

Thanks!

**Comment by juanf** [comment]
Hi @mbordash, you can pass an instance of Redis to the init method like this:

```
<?php

$persistence = JuanF\Lib\Persistence\Redis::init( $redis );

$filter = new BloomFilter($persistence);
```
